# Dependencies
markdown:           redcarpet
highlighter:        pygments
redcarpet:
  extensions:       ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

# Permalinks
permalink:          pretty

#Layout
excerpt_separator:  <!--more-->

# Setup
title:              fedtechrants.
tagline:            blog on programming computers.
url:                "http://blog.federicomaffei.com"
paginate:           5
baseurl:	        /
author:
  name:             Federico Maffei
  url:              https://github.com/federicomaffei
  email:            federico.maffei@gmail.com

# Custom vars
version:            1.0.0
github:
  repo:             https://github.com/poole/poole
